---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(modelr)
```

```{r}
project_management <- read_csv("project_management.csv")
summary(project_management)
```

```{r}
project <- project_management %>%
  select(estimated_length, actual_length)
  project
```

#Plot the data
```{r}
project %>%
  ggplot(aes(x = actual_length, y = estimated_length)) +
  geom_point()
```

```{r}
project_plot <- project %>%
  ggplot(aes(x = actual_length, y = estimated_length)) +
  geom_point() +
  aes(label = 1:nrow(project)) #Trying to apply label, not sure ho to do this
project_plot
```

The point actual length which is approximately 40 seems like an outlier as it seems more distanced than most of the other data.

```{r}
model <- lm(formula = actual_length ~ estimated_length, data = project)
model
```

```{r}
fitted(model)
```

```{r}
new_model <- lm(formula = project$actual_length ~ project$estimated_length)
new_model
```

```{r}
project %>%
  ggplot(aes(x = actual_length)) +
  geom_point(aes(y = estimated_length)) +
  geom_line(aes(y = pred), col = "red") #Need another library maybe?
```

